<?php
/**
 * PaymentsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magpie API Documentation
 *
 * Magpie API for QRPh and Disbursement services
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MagpiePay\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use MagpiePay\ApiException;
use MagpiePay\Configuration;
use MagpiePay\FormDataProcessor;
use MagpiePay\HeaderSelector;
use MagpiePay\ObjectSerializer;

/**
 * PaymentsApi Class Doc Comment
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getPaymentV1PaymentsPaymentIdGet' => [
            'application/json',
        ],
        'listPaymentsV1PaymentsGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getPaymentV1PaymentsPaymentIdGet
     *
     * Get payment
     *
     * @param  string $payment_id payment_id (required)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentV1PaymentsPaymentIdGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MagpiePay\Model\PaymentSingleResponse|\MagpiePay\Model\HTTPValidationError
     */
    public function getPaymentV1PaymentsPaymentIdGet($payment_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPaymentV1PaymentsPaymentIdGet'][0])
    {
        list($response) = $this->getPaymentV1PaymentsPaymentIdGetWithHttpInfo($payment_id, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation getPaymentV1PaymentsPaymentIdGetWithHttpInfo
     *
     * Get payment
     *
     * @param  string $payment_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentV1PaymentsPaymentIdGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MagpiePay\Model\PaymentSingleResponse|\MagpiePay\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentV1PaymentsPaymentIdGetWithHttpInfo($payment_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPaymentV1PaymentsPaymentIdGet'][0])
    {
        $request = $this->getPaymentV1PaymentsPaymentIdGetRequest($payment_id, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\PaymentSingleResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MagpiePay\Model\PaymentSingleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\PaymentSingleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPaymentV1PaymentsPaymentIdGetAsync
     *
     * Get payment
     *
     * @param  string $payment_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentV1PaymentsPaymentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentV1PaymentsPaymentIdGetAsync($payment_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPaymentV1PaymentsPaymentIdGet'][0])
    {
        return $this->getPaymentV1PaymentsPaymentIdGetAsyncWithHttpInfo($payment_id, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentV1PaymentsPaymentIdGetAsyncWithHttpInfo
     *
     * Get payment
     *
     * @param  string $payment_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentV1PaymentsPaymentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentV1PaymentsPaymentIdGetAsyncWithHttpInfo($payment_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPaymentV1PaymentsPaymentIdGet'][0])
    {
        $returnType = '\MagpiePay\Model\PaymentSingleResponse';
        $request = $this->getPaymentV1PaymentsPaymentIdGetRequest($payment_id, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPaymentV1PaymentsPaymentIdGet'
     *
     * @param  string $payment_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentV1PaymentsPaymentIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaymentV1PaymentsPaymentIdGetRequest($payment_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPaymentV1PaymentsPaymentIdGet'][0])
    {

        // verify the required parameter 'payment_id' is set
        if ($payment_id === null || (is_array($payment_id) && count($payment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payment_id when calling getPaymentV1PaymentsPaymentIdGet'
            );
        }




        $resourcePath = '/v1/payments/{payment_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($payment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'payment_id' . '}',
                ObjectSerializer::toPathValue($payment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listPaymentsV1PaymentsGet
     *
     * List payments
     *
     * @param  int|null $limit Number of payments to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentsV1PaymentsGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MagpiePay\Model\PaymentCollectionResponse|\MagpiePay\Model\HTTPValidationError
     */
    public function listPaymentsV1PaymentsGet($limit = 50, $cursor = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPaymentsV1PaymentsGet'][0])
    {
        list($response) = $this->listPaymentsV1PaymentsGetWithHttpInfo($limit, $cursor, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation listPaymentsV1PaymentsGetWithHttpInfo
     *
     * List payments
     *
     * @param  int|null $limit Number of payments to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentsV1PaymentsGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MagpiePay\Model\PaymentCollectionResponse|\MagpiePay\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listPaymentsV1PaymentsGetWithHttpInfo($limit = 50, $cursor = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPaymentsV1PaymentsGet'][0])
    {
        $request = $this->listPaymentsV1PaymentsGetRequest($limit, $cursor, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\PaymentCollectionResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MagpiePay\Model\PaymentCollectionResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\PaymentCollectionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listPaymentsV1PaymentsGetAsync
     *
     * List payments
     *
     * @param  int|null $limit Number of payments to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentsV1PaymentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentsV1PaymentsGetAsync($limit = 50, $cursor = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPaymentsV1PaymentsGet'][0])
    {
        return $this->listPaymentsV1PaymentsGetAsyncWithHttpInfo($limit, $cursor, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listPaymentsV1PaymentsGetAsyncWithHttpInfo
     *
     * List payments
     *
     * @param  int|null $limit Number of payments to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentsV1PaymentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentsV1PaymentsGetAsyncWithHttpInfo($limit = 50, $cursor = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPaymentsV1PaymentsGet'][0])
    {
        $returnType = '\MagpiePay\Model\PaymentCollectionResponse';
        $request = $this->listPaymentsV1PaymentsGetRequest($limit, $cursor, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listPaymentsV1PaymentsGet'
     *
     * @param  int|null $limit Number of payments to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentsV1PaymentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listPaymentsV1PaymentsGetRequest($limit = 50, $cursor = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPaymentsV1PaymentsGet'][0])
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.listPaymentsV1PaymentsGet, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.listPaymentsV1PaymentsGet, must be bigger than or equal to 1.');
        }
        




        $resourcePath = '/v1/payments/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
