<?php
/**
 * PayoutsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magpie API Documentation
 *
 * Magpie API for QRPh and Disbursement services
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MagpiePay\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use MagpiePay\ApiException;
use MagpiePay\Configuration;
use MagpiePay\FormDataProcessor;
use MagpiePay\HeaderSelector;
use MagpiePay\ObjectSerializer;

/**
 * PayoutsApi Class Doc Comment
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayoutsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createPayoutV1PayoutsPost' => [
            'application/json',
        ],
        'getPayoutV1PayoutsPayoutIdGet' => [
            'application/json',
        ],
        'listPayoutsV1PayoutsGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createPayoutV1PayoutsPost
     *
     * Create a payout
     *
     * @param  \MagpiePay\Model\PayoutCreateRequest $payout_create_request payout_create_request (required)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPayoutV1PayoutsPost'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MagpiePay\Model\PayoutSingleResponse|\MagpiePay\Model\HTTPValidationError
     */
    public function createPayoutV1PayoutsPost($payout_create_request, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createPayoutV1PayoutsPost'][0])
    {
        list($response) = $this->createPayoutV1PayoutsPostWithHttpInfo($payout_create_request, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation createPayoutV1PayoutsPostWithHttpInfo
     *
     * Create a payout
     *
     * @param  \MagpiePay\Model\PayoutCreateRequest $payout_create_request (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPayoutV1PayoutsPost'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MagpiePay\Model\PayoutSingleResponse|\MagpiePay\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createPayoutV1PayoutsPostWithHttpInfo($payout_create_request, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createPayoutV1PayoutsPost'][0])
    {
        $request = $this->createPayoutV1PayoutsPostRequest($payout_create_request, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\PayoutSingleResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MagpiePay\Model\PayoutSingleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\PayoutSingleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createPayoutV1PayoutsPostAsync
     *
     * Create a payout
     *
     * @param  \MagpiePay\Model\PayoutCreateRequest $payout_create_request (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPayoutV1PayoutsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPayoutV1PayoutsPostAsync($payout_create_request, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createPayoutV1PayoutsPost'][0])
    {
        return $this->createPayoutV1PayoutsPostAsyncWithHttpInfo($payout_create_request, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createPayoutV1PayoutsPostAsyncWithHttpInfo
     *
     * Create a payout
     *
     * @param  \MagpiePay\Model\PayoutCreateRequest $payout_create_request (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPayoutV1PayoutsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPayoutV1PayoutsPostAsyncWithHttpInfo($payout_create_request, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createPayoutV1PayoutsPost'][0])
    {
        $returnType = '\MagpiePay\Model\PayoutSingleResponse';
        $request = $this->createPayoutV1PayoutsPostRequest($payout_create_request, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createPayoutV1PayoutsPost'
     *
     * @param  \MagpiePay\Model\PayoutCreateRequest $payout_create_request (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createPayoutV1PayoutsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createPayoutV1PayoutsPostRequest($payout_create_request, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createPayoutV1PayoutsPost'][0])
    {

        // verify the required parameter 'payout_create_request' is set
        if ($payout_create_request === null || (is_array($payout_create_request) && count($payout_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payout_create_request when calling createPayoutV1PayoutsPost'
            );
        }




        $resourcePath = '/v1/payouts/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payout_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payout_create_request));
            } else {
                $httpBody = $payout_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPayoutV1PayoutsPayoutIdGet
     *
     * Get payout
     *
     * @param  string $payout_id payout_id (required)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutV1PayoutsPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MagpiePay\Model\PayoutSingleResponse|\MagpiePay\Model\HTTPValidationError
     */
    public function getPayoutV1PayoutsPayoutIdGet($payout_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPayoutV1PayoutsPayoutIdGet'][0])
    {
        list($response) = $this->getPayoutV1PayoutsPayoutIdGetWithHttpInfo($payout_id, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation getPayoutV1PayoutsPayoutIdGetWithHttpInfo
     *
     * Get payout
     *
     * @param  string $payout_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutV1PayoutsPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MagpiePay\Model\PayoutSingleResponse|\MagpiePay\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPayoutV1PayoutsPayoutIdGetWithHttpInfo($payout_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPayoutV1PayoutsPayoutIdGet'][0])
    {
        $request = $this->getPayoutV1PayoutsPayoutIdGetRequest($payout_id, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\PayoutSingleResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MagpiePay\Model\PayoutSingleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\PayoutSingleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPayoutV1PayoutsPayoutIdGetAsync
     *
     * Get payout
     *
     * @param  string $payout_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutV1PayoutsPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPayoutV1PayoutsPayoutIdGetAsync($payout_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPayoutV1PayoutsPayoutIdGet'][0])
    {
        return $this->getPayoutV1PayoutsPayoutIdGetAsyncWithHttpInfo($payout_id, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPayoutV1PayoutsPayoutIdGetAsyncWithHttpInfo
     *
     * Get payout
     *
     * @param  string $payout_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutV1PayoutsPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPayoutV1PayoutsPayoutIdGetAsyncWithHttpInfo($payout_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPayoutV1PayoutsPayoutIdGet'][0])
    {
        $returnType = '\MagpiePay\Model\PayoutSingleResponse';
        $request = $this->getPayoutV1PayoutsPayoutIdGetRequest($payout_id, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPayoutV1PayoutsPayoutIdGet'
     *
     * @param  string $payout_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayoutV1PayoutsPayoutIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPayoutV1PayoutsPayoutIdGetRequest($payout_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getPayoutV1PayoutsPayoutIdGet'][0])
    {

        // verify the required parameter 'payout_id' is set
        if ($payout_id === null || (is_array($payout_id) && count($payout_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payout_id when calling getPayoutV1PayoutsPayoutIdGet'
            );
        }




        $resourcePath = '/v1/payouts/{payout_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($payout_id !== null) {
            $resourcePath = str_replace(
                '{' . 'payout_id' . '}',
                ObjectSerializer::toPathValue($payout_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listPayoutsV1PayoutsGet
     *
     * List payouts
     *
     * @param  int|null $limit Number of payouts to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $reference_id Filter payouts by reference ID. (optional)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayoutsV1PayoutsGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MagpiePay\Model\PayoutCollectionResponse|\MagpiePay\Model\HTTPValidationError
     */
    public function listPayoutsV1PayoutsGet($limit = 50, $cursor = null, $reference_id = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPayoutsV1PayoutsGet'][0])
    {
        list($response) = $this->listPayoutsV1PayoutsGetWithHttpInfo($limit, $cursor, $reference_id, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation listPayoutsV1PayoutsGetWithHttpInfo
     *
     * List payouts
     *
     * @param  int|null $limit Number of payouts to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $reference_id Filter payouts by reference ID. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayoutsV1PayoutsGet'] to see the possible values for this operation
     *
     * @throws \MagpiePay\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MagpiePay\Model\PayoutCollectionResponse|\MagpiePay\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listPayoutsV1PayoutsGetWithHttpInfo($limit = 50, $cursor = null, $reference_id = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPayoutsV1PayoutsGet'][0])
    {
        $request = $this->listPayoutsV1PayoutsGetRequest($limit, $cursor, $reference_id, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\PayoutCollectionResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MagpiePay\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MagpiePay\Model\PayoutCollectionResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\PayoutCollectionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MagpiePay\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listPayoutsV1PayoutsGetAsync
     *
     * List payouts
     *
     * @param  int|null $limit Number of payouts to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $reference_id Filter payouts by reference ID. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayoutsV1PayoutsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPayoutsV1PayoutsGetAsync($limit = 50, $cursor = null, $reference_id = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPayoutsV1PayoutsGet'][0])
    {
        return $this->listPayoutsV1PayoutsGetAsyncWithHttpInfo($limit, $cursor, $reference_id, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listPayoutsV1PayoutsGetAsyncWithHttpInfo
     *
     * List payouts
     *
     * @param  int|null $limit Number of payouts to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $reference_id Filter payouts by reference ID. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayoutsV1PayoutsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPayoutsV1PayoutsGetAsyncWithHttpInfo($limit = 50, $cursor = null, $reference_id = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPayoutsV1PayoutsGet'][0])
    {
        $returnType = '\MagpiePay\Model\PayoutCollectionResponse';
        $request = $this->listPayoutsV1PayoutsGetRequest($limit, $cursor, $reference_id, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listPayoutsV1PayoutsGet'
     *
     * @param  int|null $limit Number of payouts to return (1-100). (optional, default to 50)
     * @param  string|null $cursor Cursor returned from the previous page. (optional)
     * @param  string|null $reference_id Filter payouts by reference ID. (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayoutsV1PayoutsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listPayoutsV1PayoutsGetRequest($limit = 50, $cursor = null, $reference_id = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['listPayoutsV1PayoutsGet'][0])
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PayoutsApi.listPayoutsV1PayoutsGet, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PayoutsApi.listPayoutsV1PayoutsGet, must be bigger than or equal to 1.');
        }
        





        $resourcePath = '/v1/payouts/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $reference_id,
            'reference_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
