<?php
/**
 * PayoutsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magpie API Documentation
 *
 * Magpie API for QRPh and Disbursement services
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MagpiePay\Test\Api;

use \MagpiePay\Configuration;
use \MagpiePay\ApiException;
use \MagpiePay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PayoutsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayoutsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPayoutV1PayoutsPost
     *
     * Create a payout.
     *
     */
    public function testCreatePayoutV1PayoutsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPayoutV1PayoutsPayoutIdGet
     *
     * Get payout.
     *
     */
    public function testGetPayoutV1PayoutsPayoutIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPayoutsV1PayoutsGet
     *
     * List payouts.
     *
     */
    public function testListPayoutsV1PayoutsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
