<?php
/**
 * QRPhRequestsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magpie API Documentation
 *
 * Magpie API for QRPh and Disbursement services
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MagpiePay\Test\Api;

use \MagpiePay\Configuration;
use \MagpiePay\ApiException;
use \MagpiePay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * QRPhRequestsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MagpiePay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class QRPhRequestsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelQrphV1QrphIdCancelPost
     *
     * Cancel a QRPh request.
     *
     */
    public function testCancelQrphV1QrphIdCancelPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createQrphV1QrphPost
     *
     * Create a QRPh request.
     *
     */
    public function testCreateQrphV1QrphPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getQrphStatusV1QrphIdGet
     *
     * Get QRPh status.
     *
     */
    public function testGetQrphStatusV1QrphIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listQrphV1QrphGet
     *
     * List QRPh requests.
     *
     */
    public function testListQrphV1QrphGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
